services:
  test-alpine-edge:
    build:
      context: .
      dockerfile: test/docker/alpine-edge
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-alpine-latest:
    build:
      context: .
      dockerfile: test/docker/alpine-latest
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-archlinux:
    build:
      context: .
      dockerfile: test/docker/archlinux
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-centos-stream9:
    build:
      context: .
      dockerfile: test/docker/centos-stream9
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-debian-stable:
    build:
      context: .
      dockerfile: test/docker/debian-stable
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-debian-testing:
    build:
      context: .
      dockerfile: test/docker/debian-testing
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-fedora-41:
    build:
      context: .
      dockerfile: test/docker/fedora-41
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-fedora-42:
    build:
      context: .
      dockerfile: test/docker/fedora-42
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-opensuse-leap:
    build:
      context: .
      dockerfile: test/docker/opensuse-leap
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-opensuse-tumbleweed:
    build:
      context: .
      dockerfile: test/docker/opensuse-tumbleweed
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-ubuntu-2204:
    build:
      context: .
      dockerfile: test/docker/ubuntu-2204
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
  test-ubuntu-2404:
    build:
      context: .
      dockerfile: test/docker/ubuntu-2404
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
